version: "3"
services:

  djangoapp:
    build: .
    volumes:
      - .:/code
      - static_volume:/opt/services/djangoapp/static/
      - media_volume:/opt/services/djangoapp/media/
    networks:
      - nginx_network
      - postgre_blogdb_network
    depends_on:
      - postgre_blogdb
  
  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./docker-config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/djangoapp/static/
      - media_volume:/opt/services/djangoapp/media/
    depends_on:
      - djangoapp
    networks:
      - nginx_network
  
  postgre_blogdb:
    image: postgres:latest
    env_file:
      - docker-config/db/databasepostgresql_env.env
    networks:
      - postgre_blogdb_network
    volumes:
      - postgre_blogdb_volume:/var/lib/postgresql/data


networks:
  nginx_network:
    driver: bridge
  postgre_blogdb_network:
    driver: bridge

volumes:
  postgre_blogdb_volume:
  static_volume:
  media_volume:

    

